---
title: "AssociationBtwCollegeMajorvxIncome"
author: "Prafull"
date: "October 26, 2018"
output: rmarkdown::github_document
---
####data 
```{r}

library(collegeIncome)
data("college")
head(college, 5)
```

####Summary of Data
```{r}
summary(college)
str(college)
```



####Data Manipulation 

```{r}

#we can see that the data has 173 observations of 19 variables which corresponds to the codebook.
#The question asks about relationship between the major category and income, so I will only look at major_category and median. There are obviously other #factors that may affect our analysis, for example: gender perc_men and perc_women, sample size (number of objects that provide income) perc_employed and #total. I assume to omit all other variables.

#Now let's factorize the data and see the relationship between our two interested values:
library(matahari)
dance_start(value = FALSE, contents = FALSE)
college$major_code = as.factor(college$major_code)
#factoring variables
college$major = as.factor(college$major)
college$major_category <- as.factor(college$major_category)
```


```{r}

boxplot(median/1000 ~ major_category, data = college, main = "Income vs. Major", ylab="Income (thousands of dollar)", las = 2)
#We can see the distribution of the median of Income of each major is not normal, they're skewed. However for the purpose of this project of practicing #linear model, I assume they're normal.
```
####Analyze
```{r}
unique(college$major_category)
```

#####fiting linear model for reference variable to be Arts
```{r}
#Ordering major_category in increasing order of alphabets
#When we apply a linear model to this data, linking Income to all Majors, the default output intercept is the mean of the referenced major (alphabet #sorted, with Agriculture first), the gradient coefficient of other majors is the difference of the mean of that major to the referenced one, and the #p-value of those coefficients is the probability of a t-test if that mean and the referenced mean is different. For example, say we want to compare #major Arts with others:
college = college[order(college$major_category),]
#summary of linear model using Arts as refrence levelby changing reference level to Arts
major_category_ref <- relevel(college$major_category, "Arts")
fit <- lm(data = college , median ~ major_category_ref)
summary(fit)$coef
```


####Storing Probability values into matrix 
```{r}
#Creating Matrix in which all  p value of summary function will be store for each major_category against each other category


A <- matrix( , 16, 16)
for (i in 1:16){
    major_category_ref <- relevel(college$major_category, as.character(unique(college$major_category)[i]))
    fit <- lm(median ~ major_category_ref,  data = college)
    tmp <- summary(fit)$coef[,4]
    tmp1 <- tmp[1:i]
    tmp1 <- c(tmp1[-1], tmp1[1])
    A[,i] = c(tmp1, tmp[-(1:i)])
}
#From this result we can get some information:
#- mean of median of Income from major Arts is 38,050
#- difference of mean of median of Income of Agriculture & Natural Resources from Arts is 5,450, and p-value of this difference is 0.31, which implies #that the difference is not significant
#- the same interpretation can be done for coefficients of other variables

#For this project, we ideally run linear regression models of income (median) vs. college major (major_catecory) for all majors as referenced. Given a #referenced level, the model coefficients will indicate the difference of the mean of other variables and the probability if they are the same.
#I will run regression model for each major as the reference. The similar probabilities are stored in a 2D matrix A.
```



```{r}
#reshaping matrix to dataframe and converting datframe from wide foramt to long format because we can use ggplot for long format data using melt function
library(reshape)
library(ggplot2)

B <- data.frame(A)
names(B) <- unique(college$major_category)
B$major <- unique(college$major_category)
Bmelt <- melt(B)
head(Bmelt)
```

####Exploratroy data Anlaysis
```{r}
g <- ggplot(Bmelt, aes(x = variable, y = major, fill = value))
g <- g + geom_tile()
g <- g + theme(axis.text.x = element_text(angle = 90)) + ylab("Major") + xlab("Major")
g <- g + ggtitle("Probability of difference in Income between Majors")
g <- g + coord_fixed(1)
g
```

```{r}
#ggplot to distinguish  values whose p value will be less than 0.25 and greater than 0.25 
g <- ggplot(Bmelt, aes(x = variable, y = major, fill = value < 0.025))
g <- g + geom_tile()
g <- g + theme(axis.text.x = element_text(angle = 90)) + ylab("Major") + xlab("Major")
g <- g + ggtitle("Probability of difference in Income between Majors")
g <- g + coord_fixed(1)
g

#Apparently, most majors have similar income, except the Business. Its income is significant different from Computers & Mathematics, Education, #Engineering, and Humanities & Liberal Arts.
#Let's try calculating how different they are from the Business:
```



```{r}
#Take business as reference level and find the values for remaing category 
major_category_ref <- relevel(college$major_category, "Business")
fit <- lm(median ~ major_category_ref, data = college)
summary(fit)$coef

business_diff <- summary(fit)$coef[-1,]
business_diff[order(business_diff[,4])[1:5],]
dance_save("C:/Users/Mahe/Desktop/material/Data_Science/Rcodes/college_major_analysis.rds")
#Clearly the 4 majors we pointed out above have lower p-value, and the fifth one (Arts) starts to have high enough p-value of 0.31.
```


